# Generated by Django 4.2.10 on 2024-03-15 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=14)),
                ("slug", models.CharField(max_length=130)),
                ("views", models.IntegerField(default=0)),
                ("timeStamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("content", models.TextField()),
            ],
        ),
    ]
