# Generated by Django 4.2.10 on 2024-03-15 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_timesastamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="timesaStamp",
        ),
    ]
