# Generated by Django 4.2.10 on 2024-03-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_remove_post_timesastamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like",
            field=models.IntegerField(default=0),
        ),
    ]
