# Generated by Django 4.2.10 on 2024-03-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("tech", "TECH"),
                    ("food", "FOOD"),
                    ("kind", "KIND"),
                    ("education", "EDUCATION"),
                    ("sports", "SPORTS"),
                    ("travel", "TRAVEL"),
                    ("health", "HEALTH"),
                    ("other", "OTHER"),
                ],
                default="tech",
                max_length=10,
            ),
        ),
    ]
