# Generated by Django 4.2.10 on 2024-03-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_post_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="like",
        ),
        migrations.AddField(
            model_name="post",
            name="Overview",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
