# Generated by Django 4.2.10 on 2024-03-21 04:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_blogcomment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="Overview",
        ),
    ]
