# Generated by Django 4.2.10 on 2024-03-27 06:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_apps"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apps",
            old_name="link",
            new_name="file",
        ),
    ]
